<project>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.juliodev</groupId>
    <artifactId>kafka-microservices</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging> <!-- Crucial: Must be pom -->

    <modules>
        <module>ProductsMicroservice</module>
        <module>EmailNotificationMicroservice</module>
        <module>CoreLibraries</module>
    </modules>
</project>